import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import fs from "fs";
import path from "path";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
*/
`;

const prod = process.argv[2] === "production";

const vaultRoot = process.env.OBSIDIAN_VAULT_ROOT;
const vaultPluginDir = vaultRoot
  ? path.join(vaultRoot, ".obsidian", "plugins", "strange-properties")
  : null;

const deployPlugin = {
  name: "deploy-to-vault",
  setup(build) {
    build.onEnd(() => {
      fs.mkdirSync(vaultPluginDir, { recursive: true });
      fs.copyFileSync("manifest.json", path.join(vaultPluginDir, "manifest.json"));
      fs.copyFileSync("styles.css", path.join(vaultPluginDir, "styles.css"));
    });
  },
};

const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: ["src/main.ts"],
  define: {
    __BUILD_TIME__: JSON.stringify(new Date().toISOString()),
  },
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtins,
  ],
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: (!prod && vaultPluginDir) ? path.join(vaultPluginDir, "main.js") : "main.js",
  minify: prod,
  plugins: (!prod && vaultPluginDir) ? [deployPlugin] : [],
});

if (prod) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
}
